// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enooukyyjevhuilxgxoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVub291a3l5amV2aHVpbHhneG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTE3OTUsImV4cCI6MjA3NDE4Nzc5NX0.4XAl5pYjNP4ngw4TfdTRtr2ITKuAd9qfjb7zgQqEOyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});